sudo: required
language: cpp
os: linux

compiler:
  - clang
  - gcc

env:
  - QT="551"
  - QT="562"
  - QT="571"
  - QT="58"
  - QT="591"

install:
  - sudo apt-add-repository -y "ppa:ubuntu-toolchain-r/test"
  - sudo apt-add-repository -y "ppa:beineri/opt-qt${QT}-trusty"
  - sudo apt-get -qq update
  - sudo apt-get install "qt${QT:0:2}base" "qt${QT:0:2}tools" "qt${QT:0:2}canvas3d" "qt${QT:0:2}svg"

before_script:
  - /opt/qt${QT:0:2}/bin/qmake --version

script:
  - /opt/qt${QT:0:2}/bin/qmake src/DominoProblem.pro
  - make
  - ./vador -cmd res/problems/problem1.xml

notifications:
  slack:
    secure: knV32lPoitJRyWBPeWKdYV5QGvNsoZV3RtodybGE3xv0Ly8LnUCMmk/ccpl+zEbOw2fkNIu0v0EsnHqtBwmnsDbQTvIQNdrJ9b7cbAq0zFNvzjHslnAcWiVW4km0w+GZ6GXopP02oeaLmtKDAmFKh5XDTgdFhm0GFJdVWN+y+Rnz7zAYKZEVCobPetfl5qr8wSqt9XZ0Fd6fosYMYHQ1V2juu1NFbAhEXYj9WZ/RUcGS1eVcQt7fs8bY4t3LWAE1rDGt++2CMF6PhokG2cCmdQpYcC2pRcfh90lDTq5FmLl0WOFcv1F8qcwlRj6a90yTaLHkgVB+Pds3+y1f8lt1jRRYmwGUuGqSVT1jEu+vco0y7SNDs5fkj2CzGZ+ptOe4DeCMF8qVhLbdQeFS6KaFZQqyv1/fFKMiiAqHVLzfVf+h6OdemMRIVCQxjV061/mEFG/DKBbLW1GAM6sG9kpUZU8MA9vCndmVRk4XmqUvZKJj9BuQLKXFZdiRj9+lz36KBWVUIhyft3Ne/Shq/DnGtMgLrMaSY9ZlGlRZDll3heqIqOTQZ8sZGuSjFTDfiRZRxAKiCCVrydQT4bu66XnZ9oXS49TsMBSoRVvLunoYfISE0U+5QMEC9ZnHefaQ+HONPV5V1PlcKpZjVexr8Hvsrxu6ofE5c8UngUq1jfbZtNs=
  email: false
